name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # @note: GitHub's official checkout action - do not change URL
      
      - name: Set default repository values
        run: |
          # Set hardcoded values for the correct repository
          echo "GITHUB_REPO_OWNER=peer-digital" >> $GITHUB_ENV
          echo "REPO_NAME=peerai" >> $GITHUB_ENV
          echo "Using hardcoded repository: peer-digital/peerai"
      
      - name: Extract repository name (for reference only)
        run: |
          # Extract repository name from full repository path
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Full repository: ${{ github.repository }}"
          echo "Repository name: $REPO_NAME"
          echo "NOTE: Using hardcoded repository peer-digital/peerai for deployment"
      
      - name: Verify GitHub token
        run: |
          # Verify repository access using GitHub token
          echo "Testing repository access..."
          REPO_PATH="${{ env.GITHUB_REPO_OWNER }}/${{ env.REPO_NAME }}"
          echo "Checking access to repository: $REPO_PATH"
          
          # Use GitHub token for authentication
          if curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${REPO_PATH}" | grep -q "\"name\":"; then
            echo "✅ Repository access confirmed"
          else
            echo "❌ Cannot access repository"
            echo "Please ensure:"
            echo "1. The repository exists at https://github.com/${REPO_PATH}"
            echo "2. The workflow has proper permissions to access the repository"
            echo "3. The GITHUB_TOKEN has the necessary scopes"
            exit 1
          fi
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/admin-dashboard/package-lock.json
      
      - name: Build frontend
        run: |
          cd frontend/admin-dashboard
          npm ci
          npm run build
          echo "Frontend build completed"
      
      - name: Make scripts executable
        run: |
          chmod +x ./scripts/*.sh
      
      - name: Transfer scripts and built frontend via SCP
        uses: appleboy/scp-action@v0.1.4  # @note: Reliable SCP action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "scripts/,deployment/,frontend/admin-dashboard/dist/"
          target: "/home/ubuntu/"
          strip_components: 0
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
      
      - name: Ensure scripts are executable
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            chmod +x /home/ubuntu/scripts/*.sh
            echo "Made all scripts executable"
            # Copy the latest deploy script to the peer-ai directory
            cp /home/ubuntu/scripts/deploy.sh /home/ubuntu/peer-ai/scripts/
            echo "Copied latest deploy.sh to peer-ai directory"
      
      - name: Run deployment script
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            cd /home/ubuntu/peer-ai && ./scripts/deploy.sh
      
      - name: Test database connection
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            cd /home/ubuntu/peer-ai && python3 backend/create_model_tables.py
      
      - name: Check deployment status
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            cd /home/ubuntu/peer-ai && ./scripts/check_deployment.sh 