name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # @note: GitHub's official checkout action - do not change URL
      
      - name: Make deploy script executable
        run: |
          chmod +x ./scripts/deploy.sh
      
      - name: Transfer deploy script via SCP
        uses: appleboy/scp-action@v0.1.4  # @note: Reliable SCP action for GitHub Actions
        with:
          host: 158.174.210.91  # @url: Production VM IP
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "scripts/deploy.sh"
          target: "/home/ubuntu/peer-ai/scripts/"
          strip_components: 0
          use_insecure_cipher: true
      
      - name: Run deployment script
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91  # @url: Production VM IP
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          use_insecure_cipher: true
          envs: |
            DATABASE_URL
            EXTERNAL_LLM_API_KEY
            HOSTED_LLM_API_KEY
            JWT_SECRET_KEY
            GOOGLE_SERVICE_ACCOUNT_CREDS
          env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            EXTERNAL_LLM_API_KEY: ${{ secrets.EXTERNAL_LLM_API_KEY }}
            HOSTED_LLM_API_KEY: ${{ secrets.HOSTED_LLM_API_KEY }}
            JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
            GOOGLE_SERVICE_ACCOUNT_CREDS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDS }}
          script: |
            cd /home/ubuntu/peer-ai && ./scripts/deploy.sh
      
      - name: Check deployment status
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91  # @url: Production VM IP
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          use_insecure_cipher: true
          script: |
            cd /home/ubuntu/peer-ai && ./scripts/check_deployment.sh 