name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # @note: GitHub's official checkout action - do not change URL
      
      - name: Set default repository values
        run: |
          # Set hardcoded values for the correct repository
          echo "GITHUB_REPO_OWNER=peer-digital" >> $GITHUB_ENV
          echo "REPO_NAME=peerai" >> $GITHUB_ENV
          echo "Using hardcoded repository: peer-digital/peerai"
      
      - name: Extract repository name (for reference only)
        run: |
          # Extract repository name from full repository path
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Full repository: ${{ github.repository }}"
          echo "Repository name: $REPO_NAME"
          echo "NOTE: Using hardcoded repository peer-digital/peerai for deployment"
      
      - name: Verify GitHub token
        run: |
          # For public repositories, we don't need to verify repository access with a token
          # Just check if the repository exists
          echo "Testing repository access..."
          REPO_PATH="${{ env.GITHUB_REPO_OWNER }}/${{ env.REPO_NAME }}"
          echo "Checking access to repository: $REPO_PATH"
          if curl -s "https://api.github.com/repos/${REPO_PATH}" | grep -q "\"name\":"; then
            echo "✅ Repository access confirmed"
          else
            echo "❌ Cannot access repository"
            echo "Please ensure the repository exists at https://github.com/${REPO_PATH}"
            exit 1
          fi
      
      # Setup Node.js for frontend build
      - name: Setup Node.js
        uses: actions/setup-node@v3  # @note: GitHub's official Node.js setup action - do not change URL
        with:
          node-version: '18'  # @note: Node.js version - adjust if your project requires a different version
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      
      # Build frontend
      - name: Build frontend
        run: |
          cd frontend
          npm run build
          echo "Frontend build completed"
      
      # Create tarball of the built frontend
      - name: Create frontend tarball
        run: |
          cd frontend
          tar -czf frontend-build.tar.gz build/
          echo "Created frontend tarball"
      
      - name: Make scripts executable
        run: |
          chmod +x ./scripts/*.sh
      
      - name: Transfer scripts and frontend tarball via SCP
        uses: appleboy/scp-action@v0.1.4  # @note: Reliable SCP action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "scripts/,deployment/,frontend/frontend-build.tar.gz"
          target: "/home/ubuntu/"
          strip_components: 0
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
      
      - name: Ensure scripts are executable
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            chmod +x /home/ubuntu/scripts/*.sh
            echo "Made all scripts executable"
      
      # Deploy frontend tarball
      - name: Deploy frontend tarball
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            echo "Deploying frontend build from tarball..."
            mkdir -p /home/ubuntu/peer-ai/frontend/build
            tar -xzf /home/ubuntu/frontend/frontend-build.tar.gz -C /home/ubuntu/peer-ai/frontend/
            echo "Frontend deployment completed"
      
      - name: Run comprehensive fix before deployment
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            echo "Running comprehensive database fix before deployment..."
            chmod +x /home/ubuntu/scripts/comprehensive_fix.sh
            cd /home/ubuntu/peer-ai && /home/ubuntu/scripts/comprehensive_fix.sh || echo "Warning: Comprehensive fix had issues, but continuing deployment"
      
      - name: Run diagnostic script
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            chmod +x /home/ubuntu/scripts/diagnose_ssh.sh
            /home/ubuntu/scripts/diagnose_ssh.sh
      
      - name: Setup VM if needed
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            [ -d /home/ubuntu/peer-ai ] || /home/ubuntu/scripts/setup_vm.sh
      
      - name: Setup SSH keys
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            /home/ubuntu/scripts/setup_ssh.sh
      
      - name: Setup GitHub authentication
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          envs: GITHUB_REPO_OWNER,REPO_NAME
          script: |
            # Debug environment variables
            echo "GITHUB_REPO_OWNER: ${GITHUB_REPO_OWNER}"
            echo "REPO_NAME: ${REPO_NAME}"
            
            # Use explicit environment variables with the correct repository information
            # No token needed for public repositories
            GITHUB_USER="${GITHUB_REPO_OWNER}" GITHUB_REPO="${REPO_NAME}" /home/ubuntu/scripts/setup_github_auth.sh
        env:
          GITHUB_REPO_OWNER: ${{ env.GITHUB_REPO_OWNER }}
          REPO_NAME: ${{ env.REPO_NAME }}
      
      - name: Fix permissions
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            /home/ubuntu/scripts/fix_permissions.sh
      
      # Skip backend deployment if we're using the pre-built frontend
      - name: Run deployment script (backend only)
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            cd /home/ubuntu/peer-ai && SKIP_FRONTEND_BUILD=true ./scripts/deploy.sh || {
              echo "Deployment script failed. Attempting emergency database fix..."
              chmod +x /home/ubuntu/scripts/comprehensive_fix.sh
              cd /home/ubuntu/peer-ai && /home/ubuntu/scripts/comprehensive_fix.sh
              echo "Trying deployment again after emergency fix..."
              cd /home/ubuntu/peer-ai && SKIP_FRONTEND_BUILD=true ./scripts/deploy.sh
            }
      
      - name: Fix database migrations
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            echo "Checking if additional migration fixes are needed..."
            cd /home/ubuntu/peer-ai/backend
            source venv/bin/activate
            python -c "from sqlalchemy import create_engine, text; engine = create_engine('postgresql://peerai:peerai_password@localhost:5432/peerai_db'); result = engine.connect().execute(text('SELECT version_num FROM alembic_version')).fetchone(); print(f'Current alembic version: {result[0] if result else \"No version found\"}')"
            
            if [ -f "/home/ubuntu/scripts/fix_migration.sh" ]; then
              echo "Note: Using comprehensive fix instead of the original fix_migration.sh"
            fi
      
      - name: Fix constraint issue
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            echo "Checking if additional constraint fixes are needed..."
            cd /home/ubuntu/peer-ai/backend
            source venv/bin/activate
            
            # Create a temporary script to check constraints
            cat > /home/ubuntu/check_constraint.py << EOF
            import os
            from sqlalchemy import create_engine, text
            
            DATABASE_URL = os.environ.get('DATABASE_URL', 'postgresql://peerai:peerai_password@localhost:5432/peerai_db')
            
            try:
                engine = create_engine(DATABASE_URL)
                with engine.connect() as conn:
                    result = conn.execute(text("SELECT COUNT(*) FROM pg_constraint WHERE conname = 'uq_referrals_referee_id'")).scalar()
                    if result > 0:
                        print("needs_fix")
                    else:
                        print("no_fix_needed")
            except Exception as e:
                print(f"error: {e}")
            EOF
            
            # Run the constraint check
            constraint_check=$(python /home/ubuntu/check_constraint.py)
            
            # Take action based on the result
            if [[ $constraint_check == "needs_fix" ]]; then
                echo "Constraint still exists, running specific fix..."
                chmod +x /home/ubuntu/scripts/fix_constraint_issue.sh
                /home/ubuntu/scripts/fix_constraint_issue.sh
            elif [[ $constraint_check == "no_fix_needed" ]]; then
                echo "Constraint does not exist, comprehensive fix was successful"
            else
                echo "Error checking constraint, output: $constraint_check"
                echo "Running fix script as a precaution"
                chmod +x /home/ubuntu/scripts/fix_constraint_issue.sh
                /home/ubuntu/scripts/fix_constraint_issue.sh || echo "Fix attempt failed, continuing anyway"
            fi
            
            # Clean up
            rm -f /home/ubuntu/check_constraint.py
      
      - name: Test database connection
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            chmod +x /home/ubuntu/scripts/ssh_to_db.sh
            chmod +x /home/ubuntu/scripts/test_db.sh
            chmod +x /home/ubuntu/scripts/test_db_connection.py
            cd /home/ubuntu/peer-ai && /home/ubuntu/scripts/test_db.sh
      
      - name: Run pre-migration checks
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            echo "Running database sanity checks before database initialization..."
            cd /home/ubuntu/peer-ai/backend
            source venv/bin/activate
            
            # Print current database status
            python - << EOF
            import os
            from sqlalchemy import create_engine, text, inspect
            
            DATABASE_URL = os.environ.get('DATABASE_URL', 'postgresql://peerai:peerai_password@localhost:5432/peerai_db')
            
            try:
                engine = create_engine(DATABASE_URL)
                with engine.connect() as conn:
                    # Get migration version
                    try:
                        result = conn.execute(text("SELECT version_num FROM alembic_version")).fetchone()
                        print(f"Current migration version: {result[0] if result else 'None'}")
                    except Exception as e:
                        print(f"Error getting migration version: {e}")
                    
                    # Check for problematic constraint
                    try:
                        result = conn.execute(text("SELECT COUNT(*) FROM pg_constraint WHERE conname = 'uq_referrals_referee_id'")).scalar()
                        print(f"Constraint 'uq_referrals_referee_id' exists: {'Yes' if result > 0 else 'No'}")
                    except Exception as e:
                        print(f"Error checking constraint: {e}")
                    
                    # List tables
                    inspector = inspect(engine)
                    tables = inspector.get_table_names()
                    print(f"Tables in database: {', '.join(tables) if tables else 'None'}")
            except Exception as e:
                print(f"Error connecting to database: {e}")
            EOF
            
            echo "Database sanity check complete. Continue with initialization."
      
      - name: Initialize database
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            cd /home/ubuntu/peer-ai && ./scripts/init_db_auto.sh || {
              echo "Database initialization failed. Attempting emergency fix..."
              chmod +x /home/ubuntu/scripts/run_emergency_fix.sh
              /home/ubuntu/scripts/run_emergency_fix.sh || echo "Emergency fix failed, but continuing deployment"
              echo "Retrying database initialization..."
              cd /home/ubuntu/peer-ai && ./scripts/init_db_auto.sh || echo "Database initialization still failed, continuing deployment"
            }
      
      - name: Run fix scripts
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            cd /home/ubuntu/peer-ai && ./scripts/debug_migrations.sh || echo "Debug migrations script failed, continuing"
            cd /home/ubuntu/peer-ai && ./scripts/fix_github_actions.sh || echo "Fix GitHub Actions script failed, continuing"
            cd /home/ubuntu/peer-ai && ./scripts/fix_frontend_build.sh || echo "Fix frontend build script failed, continuing"
      
      - name: Check deployment status
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Disable host key checking to handle host key changes
          use_insecure_cipher: true
          script: |
            cd /home/ubuntu/peer-ai && ./scripts/check_deployment.sh 