name: Build and Deploy Frontend & Backend

on:
  push:
    branches:
      - main  # @note: Trigger deployment on push to main branch
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # @note: GitHub's official checkout action - do not change URL
      
      # --- Frontend Build Steps ---
      - name: Setup Node.js
        uses: actions/setup-node@v4  # @note: Latest Node.js setup action
        with:
          node-version: '20'  # @note: Node.js version for frontend build
          cache: 'npm'  # @note: Cache npm dependencies for faster builds
      
      - name: Install Frontend Dependencies
        run: |
          cd frontend/admin-dashboard
          npm ci  # @note: Clean install for reproducible builds
      
      - name: Build Frontend
        run: |
          cd frontend/admin-dashboard
          npm run build  # @note: Build frontend application
        env:
          VITE_API_BASE_URL: http://158.174.210.91  # @url: Production VM IP
          VITE_APP_ENV: production
          VITE_AUTH_ENABLED: true
      
      - name: Create Frontend Tarball
        run: |
          cd frontend/admin-dashboard
          tar -czvf ../../frontend-build.tar.gz dist/  # @note: Create tarball of build output
      
      # --- SSH Setup ---
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0  # @note: Secure SSH key handling
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add remote host to known_hosts
        run: ssh-keyscan -H 158.174.210.91 >> ~/.ssh/known_hosts  # @url: Production VM IP
      
      - name: Make deploy script executable
        run: |
          chmod +x ./scripts/deploy.sh
      
      # --- Deployment Steps ---
      - name: Deploy Files via Rsync
        run: |
          rsync -avz --delete \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='node_modules/' \
            --exclude='frontend-build.tar.gz' \
            --exclude='frontend/admin-dashboard/node_modules/' \
            --exclude='frontend/admin-dashboard/dist/' \
            ./ ubuntu@158.174.210.91:/home/ubuntu/peer-ai/
          
          # Copy tarball and deploy script separately
          scp ./frontend-build.tar.gz ubuntu@158.174.210.91:/home/ubuntu/peer-ai/
          scp ./scripts/deploy.sh ubuntu@158.174.210.91:/home/ubuntu/peer-ai/scripts/
      
      - name: Debug Environment
        run: |
          echo "Checking if environment variables are set (values hidden):"
          if [ ! -z "${{ secrets.DATABASE_URL }}" ]; then echo "DATABASE_URL is set"; else echo "Warning: DATABASE_URL is NOT set"; fi
          if [ ! -z "${{ secrets.EXTERNAL_LLM_API_KEY }}" ]; then echo "EXTERNAL_LLM_API_KEY is set"; else echo "Warning: EXTERNAL_LLM_API_KEY is NOT set"; fi
          if [ ! -z "${{ secrets.HOSTED_LLM_API_KEY }}" ]; then echo "HOSTED_LLM_API_KEY is set"; else echo "Warning: HOSTED_LLM_API_KEY is NOT set"; fi
          if [ ! -z "${{ secrets.JWT_SECRET_KEY }}" ]; then echo "JWT_SECRET_KEY is set"; else echo "Warning: JWT_SECRET_KEY is NOT set"; fi
          if [ ! -z "${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDS }}" ]; then echo "GOOGLE_SERVICE_ACCOUNT_CREDS is set"; else echo "Warning: GOOGLE_SERVICE_ACCOUNT_CREDS is NOT set"; fi
      
      - name: Extract Frontend & Run Deploy Script
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          EXTERNAL_LLM_API_KEY: ${{ secrets.EXTERNAL_LLM_API_KEY }}
          HOSTED_LLM_API_KEY: ${{ secrets.HOSTED_LLM_API_KEY }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          GOOGLE_SERVICE_ACCOUNT_CREDS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDS }}
          RATE_LIMIT_DAILY: ${{ secrets.RATE_LIMIT_DAILY }}  # @note: Daily rate limit for API calls
          # @note: Add any other non-secret env vars needed
          PORT: 8000
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
          RATE_LIMIT_MINUTE: 60
          ENVIRONMENT: production
          ALLOWED_ORIGIN: http://158.174.210.91
          EXTERNAL_MODEL: mistral-tiny
          EXTERNAL_LLM_URL: https://api.mistral.ai/v1/chat/completions
          DEBUG: false
          MOCK_MODE: false
          LOG_LEVEL: INFO
          GOOGLE_WORKSPACE_ADMIN_EMAIL: adam.falkenberg@peerdigital.se
          NOTIFICATION_EMAIL_ALIAS: notifications@peerdigital.se
          VITE_TEST_EMAIL: admin@peerai.se
          VITE_TEST_PASSWORD: admin123
          JWT_ALGORITHM: HS256
          VITE_API_BASE_URL: http://158.174.210.91
          VITE_APP_ENV: production
          VITE_AUTH_ENABLED: true
        with:
          host: 158.174.210.91  # @url: Production VM IP
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          use_insecure_cipher: true
          envs: DATABASE_URL,EXTERNAL_LLM_API_KEY,HOSTED_LLM_API_KEY,JWT_SECRET_KEY,GOOGLE_SERVICE_ACCOUNT_CREDS,PORT,ACCESS_TOKEN_EXPIRE_MINUTES,RATE_LIMIT_MINUTE,ENVIRONMENT,ALLOWED_ORIGIN,EXTERNAL_MODEL,EXTERNAL_LLM_URL,DEBUG,MOCK_MODE,LOG_LEVEL,GOOGLE_WORKSPACE_ADMIN_EMAIL,NOTIFICATION_EMAIL_ALIAS,VITE_TEST_EMAIL,VITE_TEST_PASSWORD,JWT_ALGORITHM,VITE_API_BASE_URL,VITE_APP_ENV,VITE_AUTH_ENABLED,RATE_LIMIT_DAILY
          script: |
            # Navigate to the app directory
            cd /home/ubuntu/peer-ai
            echo "Current directory: $(pwd)"

            # --- Ensure Backend Code / requirements.txt is present ---
            echo "Checking for requirements.txt..."
            ls -l requirements.txt || { echo "ERROR: requirements.txt not found!"; exit 1; }

            # --- Setup Python Virtual Environment & Install Dependencies ---
            echo "Setting up Python virtual environment..."
            python3 -m venv .venv  # Creates .venv if it doesn't exist, ensures it's valid
            echo "Activating virtual environment (for this script block)..."
            source .venv/bin/activate  # Activate venv to use its pip
            echo "Installing/updating dependencies from requirements.txt (verbose)..."
            # Add -v for verbose output from pip
            pip install -v -r requirements.txt || { echo "ERROR: pip install failed!"; exit 1; }  # Exit if pip fails
            echo "Verifying uvicorn installation..."
            ls -l .venv/bin/uvicorn || { echo "ERROR: uvicorn not found after pip install!"; exit 1; }
            .venv/bin/uvicorn --version || { echo "ERROR: uvicorn command failed!"; exit 1; }
            echo "Deactivating virtual environment (for this script block)..."
            deactivate  # Good practice, though systemd runs ExecStart directly
            echo "Python environment setup complete."

            # --- Write Google Credentials JSON File ---
            echo "Writing Google credentials to google-creds.json..."
            printf "%s" "$GOOGLE_SERVICE_ACCOUNT_CREDS" > google-creds.json
            chmod 600 google-creds.json  # Restrict permissions
            echo "Credentials file written."
            ls -l google-creds.json

            # --- Extract Frontend Build ---
            echo "Extracting frontend build..."
            mkdir -p frontend/admin-dashboard/dist
            tar -xzvf frontend-build.tar.gz -C frontend/admin-dashboard/dist --strip-components=1
            rm frontend-build.tar.gz  # Clean up tarball
            echo "Frontend build extracted successfully."

            # --- Verify ubuntu user/group ON VM ---
            echo "--- Verifying ubuntu user/group on VM (UID/GID should be 1000) ---"
            id ubuntu || echo "ERROR: Command 'id ubuntu' failed or user not found!"
            getent group ubuntu || echo "ERROR: Command 'getent group ubuntu' failed or group not found!"
            echo "-----------------------------------------"

            # --- Run Deployment Script ---
            echo "Running deployment script (./scripts/deploy.sh)..."
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh || {
              echo "Deployment script ./scripts/deploy.sh failed"
              # Attempt to get more details from systemd status
              echo "--- Attempting to get systemctl status peerai-backend.service ---"
              systemctl status peerai-backend.service --no-pager || echo "Failed to get systemctl status."
              echo "--- Attempting to get journalctl for peerai-backend.service ---"
              journalctl -u peerai-backend.service -n 50 --no-pager || echo "Failed to get journalctl logs."
              echo "----------------------------------------------------------------"
              exit 1
            }
            echo "Deployment script completed successfully."

      - name: Configure and Reload Nginx
        uses: appleboy/ssh-action@v1.0.3  # @note: Latest version for better reliability
        with:
          host: 158.174.210.91  # @url: Production VM IP
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          use_insecure_cipher: true
          script: |
            echo "Configuring Nginx..."
            # First, remove any existing configuration
            sudo rm -f /etc/nginx/conf.d/peerai.conf
            
            # Create new configuration
            NGINX_CONF='server {
              listen 80;
              server_name 158.174.210.91;
              
              # Frontend static files
              location / {
                root /home/ubuntu/peer-ai/frontend/admin-dashboard/dist;
                try_files $uri $uri/ /index.html;
                add_header Cache-Control "no-cache, no-store, must-revalidate";
                add_header Pragma "no-cache";
                add_header Expires "0";
              }
              
              # Backend API
              location /api/v1/ {
                proxy_pass http://localhost:8000/api/v1/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # Add CORS headers
                add_header "Access-Control-Allow-Origin" "*" always;
                add_header "Access-Control-Allow-Methods" "GET, POST, PUT, DELETE, OPTIONS" always;
                add_header "Access-Control-Allow-Headers" "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization" always;
                add_header "Access-Control-Expose-Headers" "Content-Length,Content-Range" always;
                
                # Handle OPTIONS method
                if ($request_method = "OPTIONS") {
                  add_header "Access-Control-Allow-Origin" "*" always;
                  add_header "Access-Control-Allow-Methods" "GET, POST, PUT, DELETE, OPTIONS" always;
                  add_header "Access-Control-Allow-Headers" "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization" always;
                  add_header "Access-Control-Max-Age" 1728000;
                  add_header "Content-Type" "text/plain; charset=utf-8";
                  add_header "Content-Length" 0;
                  return 204;
                }
              }
              
              # Health check endpoint
              location /health {
                proxy_pass http://localhost:8000/health;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
              }
            }'
            echo "$NGINX_CONF" | sudo tee /etc/nginx/conf.d/peerai.conf

            echo "Checking Nginx configuration..."
            sudo nginx -t || { echo "ERROR: Nginx configuration test failed!"; exit 1; }

            echo "Reloading Nginx..."
            sudo systemctl reload nginx || { echo "ERROR: Failed to reload Nginx!"; exit 1; }

            echo "Nginx configured and reloaded."
            
            # Verify frontend files are accessible
            echo "Verifying frontend files..."
            ls -l /home/ubuntu/peer-ai/frontend/admin-dashboard/dist || { echo "ERROR: Frontend files not found!"; exit 1; }
            
            # Check if backend service is running
            echo "Checking backend service status..."
            sudo systemctl status peerai-backend.service || { echo "ERROR: Backend service not running!"; exit 1; }
            
            # Test the login endpoint
            echo "Testing login endpoint..."
            curl -v http://localhost/api/v1/auth/login || { echo "ERROR: Login endpoint not accessible!"; exit 1; }
      
      - name: Check deployment status
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91  # @url: Production VM IP
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          use_insecure_cipher: true
          script: |
            cd /home/ubuntu/peer-ai && ./scripts/check_deployment.sh || {
              echo "Deployment check failed"
              exit 1
            } 