name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # @note: GitHub's official checkout action - do not change URL
      
      - name: Extract repository name
        run: |
          # Extract repository name from full repository path
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Full repository: ${{ github.repository }}"
          echo "Repository name: $REPO_NAME"
          # Export to GitHub environment for use in other steps
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
      
      - name: Verify GitHub token
        run: |
          # Test GitHub API access with the token
          echo "Testing GitHub API access..."
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.GH_PAT }}" https://api.github.com/user)
          echo "GitHub API HTTP Status: $HTTP_STATUS"
          
          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ GitHub token is valid"
          else
            echo "❌ GitHub token is invalid or has insufficient permissions"
            echo "Please check your GH_PAT secret in the repository settings"
            exit 1
          fi
          
          # Test repository access
          echo "Testing repository access..."
          if curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" https://api.github.com/repos/${{ github.repository }} | grep -q "\"name\":"; then
            echo "✅ Repository access confirmed"
          else
            echo "❌ Cannot access repository with the provided token"
            echo "Please ensure the token has 'repo' scope and the repository exists"
            exit 1
          fi
      
      - name: Make scripts executable
        run: |
          chmod +x ./scripts/*.sh
      
      - name: Transfer scripts via SCP
        uses: appleboy/scp-action@v0.1.4  # @note: Reliable SCP action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "scripts/,deployment/"
          target: "/home/ubuntu/"
          strip_components: 0
      
      - name: Run diagnostic script
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x /home/ubuntu/scripts/diagnose_ssh.sh
            /home/ubuntu/scripts/diagnose_ssh.sh
      
      - name: Setup VM if needed
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            [ -d /home/ubuntu/peer-ai ] || /home/ubuntu/scripts/setup_vm.sh
      
      - name: Setup SSH keys
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /home/ubuntu/scripts/setup_ssh.sh
      
      - name: Setup GitHub authentication
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GH_PAT,GITHUB_USERNAME,REPO_NAME
          script: |
            # Debug environment variables
            echo "GITHUB_USERNAME: ${GITHUB_USERNAME}"
            echo "REPO_NAME: ${REPO_NAME}"
            
            # Use explicit environment variables
            GITHUB_TOKEN="${GH_PAT}" GITHUB_USER="${GITHUB_USERNAME}" GITHUB_REPO="${REPO_NAME}" /home/ubuntu/scripts/setup_github_auth.sh
            
            # Verify GitHub authentication
            chmod +x /home/ubuntu/scripts/verify_github_auth.sh
            GITHUB_TOKEN="${GH_PAT}" GITHUB_USER="${GITHUB_USERNAME}" GITHUB_REPO="${REPO_NAME}" /home/ubuntu/scripts/verify_github_auth.sh
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # @note: Personal Access Token for GitHub authentication
          GITHUB_USERNAME: ${{ github.repository_owner }}
          REPO_NAME: ${{ env.REPO_NAME }}
      
      - name: Fix permissions
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /home/ubuntu/scripts/fix_permissions.sh
      
      - name: Run deployment script
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/peer-ai && ./scripts/deploy.sh
      
      - name: Initialize database
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/peer-ai && ./scripts/init_db_auto.sh
      
      - name: Run fix scripts
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/peer-ai && ./scripts/debug_migrations.sh || echo "Debug migrations script failed, continuing"
            cd /home/ubuntu/peer-ai && ./scripts/fix_github_actions.sh || echo "Fix GitHub Actions script failed, continuing"
            cd /home/ubuntu/peer-ai && ./scripts/fix_frontend_build.sh || echo "Fix frontend build script failed, continuing"
      
      - name: Check deployment status
        uses: appleboy/ssh-action@v1.0.0  # @note: Reliable SSH action for GitHub Actions
        with:
          host: 158.174.210.91
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/peer-ai && ./scripts/check_deployment.sh 